export type Trip={id:string;profileId:string;entryDate:string;exitDate:string|null;source:'MANUAL'|'AUTO';note:string;countries:string[]};
export type Profile={id:string;name:string;passportNumber:string};
export type Data={profiles:Profile[];trips:Trip[];active:string;appearance:string;color:string;sunday:boolean;notifications:boolean;tracking:boolean;lastSync?:string};
export const countries=[['AT','Austria'],['BE','Belgium'],['BG','Bulgaria'],['HR','Croatia'],['CZ','Czechia'],['DK','Denmark'],['EE','Estonia'],['FI','Finland'],['FR','France'],['DE','Germany'],['GR','Greece'],['HU','Hungary'],['IS','Iceland'],['IT','Italy'],['LV','Latvia'],['LI','Liechtenstein'],['LT','Lithuania'],['LU','Luxembourg'],['MT','Malta'],['NL','Netherlands'],['NO','Norway'],['PL','Poland'],['PT','Portugal'],['RO','Romania'],['SK','Slovakia'],['SI','Slovenia'],['ES','Spain'],['SE','Sweden'],['CH','Switzerland']];
export const initial:Data={profiles:[{id:'default',name:'My passport',passportNumber:''}],trips:[],active:'default',appearance:'system',color:'blue',sunday:false,notifications:false,tracking:false};
export const themes:Record<string,[string,string]>={blue:['#1e66e0','#3b82f6'],green:['#158e45','#22c55e'],purple:['#7e3ad1','#a855f7'],orange:['#c85603','#f97316'],pink:['#c2317c','#ec4899'],teal:['#0c8b7f','#14b8a6'],slate:['#45526b','#94a3b8'],red:['#c02323','#ef4444']};
export function day(s:string){return Math.floor(Date.parse(s+'T00:00:00Z')/86400000)}
export function iso(n:number){return new Date(n*86400000).toISOString().slice(0,10)}
export function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function validDate(s:unknown):s is string{return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(day(s))&&iso(day(s))===s&&s>='1900-01-01'&&s<='2200-12-31'}
export function fmt(s:string,year=false){return new Date(s+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',...(year?{year:'numeric'}:{})})}
export function flag(code:string){return code?String.fromCodePoint(...code.toUpperCase().split('').map(c=>127397+c.charCodeAt(0))):'🌍'}
export const countryName=(code:string)=>countries.find(c=>c[0]===code)?.[1]||code;
export const tripLabel=(t:Trip)=>t.countries.map(countryName).join(', ')||'Schengen trip';
export function used(date:string,trips:Trip[]){const end=day(date),ranges=trips.map(t=>[Math.max(day(t.entryDate),end-179),Math.min(t.exitDate?day(t.exitDate):end,end)]).filter(([a,b])=>a<=b).sort((a,b)=>a[0]-b[0]);let count=0,last=-Infinity;for(const [a,b] of ranges){count+=Math.max(0,b-Math.max(a,last+1)+1);last=Math.max(last,b)}return count}
export const available=(date:string,trips:Trip[])=>Math.max(0,90-used(date,trips));
export const confirmed=(trips:Trip[],now:string)=>trips.filter(t=>t.entryDate<=now).map(t=>({...t,exitDate:!t.exitDate||t.exitDate>now?now:t.exitDate}));
export function recovery(trips:Trip[],now:string){const actual=confirmed(trips,now),base=available(now,actual);if(base===90)return null;for(let i=1;i<=180;i++){const d=iso(day(now)+i);if(available(d,actual)>base)return d}return null}
export function overstay(trips:Trip[],now:string){if(!trips.length)return null;const end=Math.max(day(now)+180,...trips.map(t=>day(t.exitDate||t.entryDate)+180));for(let d=day(now);d<=end;d++)if(used(iso(d),trips)>90)return iso(d);return null}
export function status(t:Trip,trips:Trip[],now:string){const n=used(t.exitDate||(t.entryDate>now?t.entryDate:now),trips);return n>90?'Over limit':n>=80?'Close to limit':'Within limits'}
export function checkTrip(t:Trip){if(!validDate(t.entryDate)||t.exitDate!==null&&!validDate(t.exitDate))throw Error('Enter a valid entry and exit date.');if(t.exitDate&&t.exitDate<t.entryDate)throw Error('Exit date must be on or after entry date.');if(!['MANUAL','AUTO'].includes(t.source))throw Error('Invalid trip source.');if(!Array.isArray(t.countries)||t.countries.some(c=>!countries.some(x=>x[0]===c)))throw Error('Choose countries from the Schengen list.');if(typeof t.note!=='string')throw Error('Invalid trip note.');return t}
const uid=()=>crypto.randomUUID();
export function exportCsv(data:Data){const rows=[['type','profile_name','passport_number','entry_date','exit_date','source','note','countries']];for(const p of data.profiles){rows.push(['PROFILE',p.name,p.passportNumber,'','','','','']);for(const t of data.trips.filter(t=>t.profileId===p.id))rows.push(['TRIP',p.name,p.passportNumber,t.entryDate,t.exitDate||'',t.source,t.note,t.countries.map(countryName).join(', ')])}return rows.map(row=>row.map(s=>'"'+s.replaceAll('"','""')+'"').join(',')).join('\r\n')}
export function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quote=false;const s=text.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quote&&s[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}if(quote)throw Error('The CSV has an unclosed quoted field.');row.push(cell);if(row.some(Boolean))rows.push(row);return rows}
export function importBackup(text:string,base:Data):Data{let profiles:Profile[]=[],trips:Trip[]=[];let prefs:Partial<Data>={};if(text.trim().startsWith('{')){const b=JSON.parse(text);if(b.version!==1||!Array.isArray(b.profiles))throw Error('Unsupported backup format.');for(const p of b.profiles){if(typeof p.name!=='string'||!p.name.trim()||!Array.isArray(p.trips))throw Error('Invalid profile in backup.');const id=uid();profiles.push({id,name:p.name,passportNumber:p.passportNumber||''});for(const t of p.trips)trips.push(checkTrip({...t,id:uid(),profileId:id,exitDate:t.exitDate||null,note:t.note||'',countries:t.countries||[]}))}prefs={appearance:['system','light','dark'].includes(b.appearanceMode)?b.appearanceMode:'system',color:themes[b.colorThemeId]?b.colorThemeId:'blue',sunday:!!b.startWeekOnSunday}}else{const rows=parseCsv(text);if(rows.shift()?.join(',')!=='type,profile_name,passport_number,entry_date,exit_date,source,note,countries')throw Error('Choose a Schengen Tracker CSV backup.');const keys=new Map<string,string>();for(const r of rows){if(r.length!==8||!['PROFILE','TRIP'].includes(r[0]))throw Error('Invalid backup row.');const key=JSON.stringify([r[1],r[2]]);let id=keys.get(key);if(!id){id=uid();keys.set(key,id);profiles.push({id,name:r[1]||'Imported profile',passportNumber:r[2]})}if(r[0]==='TRIP'){const codes=r[7]?r[7].split(/[,;]/).map(c=>countries.find(x=>x[0].toLowerCase()===c.trim().toLowerCase()||x[1].toLowerCase()===c.trim().toLowerCase())?.[0]||c.trim()):[];trips.push(checkTrip({id:uid(),profileId:id,entryDate:r[3],exitDate:r[4]||null,source:r[5] as Trip['source'],note:r[6],countries:codes}))}}}if(!profiles.length)throw Error('The backup contains no traveler profiles.');return {...base,...prefs,profiles,trips,active:profiles[0].id,tracking:false}}
export function jsonBackup(data:Data){return {version:1,createdAt:Date.now(),appearanceMode:data.appearance,colorThemeId:data.color,startWeekOnSunday:data.sunday,profiles:data.profiles.map(p=>({...p,trips:data.trips.filter(t=>t.profileId===p.id).map(({id,profileId,...t})=>t)}))}}
